"""SIMBA_INTEL Agent Tools Package.
"""
from .registry import ExecutionResult, RiskLevel, Tool, ToolParameter, ToolRegistry, global_tool_registry
from .windows_utils import (
    close_window_or_process,
    empty_windows_recycle_bin,
    find_window_by_title_substring,
    force_focus_window,
    get_active_window_info,
    get_clipboard_text,
    get_mouse_position,
    get_system_telemetry,
    maximize_window,
    maximize_window_by_hwnd,
    minimize_window,
    minimize_window_by_hwnd,
    mouse_click,
    mouse_double_click,
    mouse_move,
    mouse_right_click,
    mouse_scroll,
    paste_clipboard,
    restore_window,
    restore_window_by_hwnd,
    send_hotkey,
    send_key,
    send_keys_sequence,
    send_unicode_text,
    set_clipboard_text,
    set_foreground_window,
    switch_to_window,
    system_power,
    wait_for_process,
    wait_for_window_by_title,
)

# Import tool modules to trigger tool registration in global_tool_registry
from . import browser_tools
from . import calculator_tools
from . import desktop_tools
from . import filesystem_tools

__all__ = [
    "ExecutionResult",
    "RiskLevel",
    "Tool",
    "ToolParameter",
    "ToolRegistry",
    "global_tool_registry",
    "set_clipboard_text",
    "get_clipboard_text",
    "paste_clipboard",
    "send_key",
    "send_keys_sequence",
    "send_hotkey",
    "send_unicode_text",
    "force_focus_window",
    "find_window_by_title_substring",
    "wait_for_window_by_title",
    "get_active_window_info",
    "set_foreground_window",
    "close_window_or_process",
    "get_system_telemetry",
    "minimize_window",
    "minimize_window_by_hwnd",
    "maximize_window",
    "maximize_window_by_hwnd",
    "restore_window",
    "restore_window_by_hwnd",
    "switch_to_window",
    "get_mouse_position",
    "mouse_click",
    "mouse_double_click",
    "mouse_right_click",
    "mouse_move",
    "mouse_scroll",
    "empty_windows_recycle_bin",
    "system_power",
]
