# Generated by Django 6.0.2 on 2026-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_is_pinned_alter_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(default='OFFLINE', max_length=50),
        ),
    ]
