# Generated by Django 6.0.2 on 2026-03-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_model_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='model_used',
        ),
    ]
