# Generated by Django 6.0.2 on 2026-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmessage_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='latency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
