# Generated by Django 6.0.5 on 2026-07-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatsession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
