# Generated by Django 6.0.5 on 2026-07-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatmessage_extra_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("avatar_url", models.URLField(blank=True)),
                ("default_model", models.CharField(default="cyber-max", max_length=50)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("cyberpunk", "Cyberpunk (default)"),
                            ("midnight-purple", "Midnight Purple"),
                            ("matrix-green", "Matrix Green"),
                            ("light", "Light"),
                        ],
                        default="cyberpunk",
                        max_length=20,
                    ),
                ),
                ("memory_enabled", models.BooleanField(default=False)),
                ("notifications_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
