# Generated by Django 6.0.5 on 2026-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_usageevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("cyberpunk", "Cyber Dark (default)"),
                    ("midnight-purple", "Midnight"),
                    ("matrix-green", "Matrix"),
                    ("nord", "Nord"),
                    ("synthwave", "Synthwave"),
                    ("purple-neon", "Purple Neon"),
                    ("ocean", "Ocean"),
                    ("minimal-dark", "Minimal Dark"),
                    ("graphite", "Graphite"),
                    ("light", "Light"),
                ],
                default="cyberpunk",
                max_length=20,
            ),
        ),
    ]
