# Generated by Django 6.0.5 on 2026-07-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_featureflag_userprofile_ban_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("block", "block"),
                    ("unblock", "unblock"),
                    ("suspend", "suspend"),
                    ("unsuspend", "unsuspend"),
                    ("ban", "ban"),
                    ("unban", "unban"),
                    ("force_logout", "force_logout"),
                    ("delete_chats", "delete_chats"),
                    ("delete_uploads", "delete_uploads"),
                    ("reset_password", "reset_password"),
                    ("verify_email", "verify_email"),
                    ("change_role", "change_role"),
                    ("add_note", "add_note"),
                    ("feature_flag_toggle", "feature_flag_toggle"),
                    ("broadcast_create", "broadcast_create"),
                    ("broadcast_deactivate", "broadcast_deactivate"),
                ],
                max_length=30,
            ),
        ),
    ]
