# Generated by Django 6.0.5 on 2026-07-15 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_alter_adminauditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="chat_securi_event_t_ad1a55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usageevent",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="chat_usagee_event_t_11577b_idx",
            ),
        ),
    ]
