# Generated by Django 6.0.5 on 2026-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_securityevent_browser_securityevent_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityevent",
            name="location",
            field=models.CharField(
                blank=True, default="Unknown Location", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="os",
            field=models.CharField(blank=True, default="Unknown OS", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_os",
            field=models.CharField(blank=True, default="Unknown OS", max_length=100),
        ),
        migrations.AddField(
            model_name="usersession",
            name="os",
            field=models.CharField(blank=True, default="Unknown OS", max_length=100),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="browser",
            field=models.CharField(
                blank=True, default="Unknown Browser", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="device",
            field=models.CharField(
                blank=True, default="Unknown Device", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="securityevent",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login_browser",
            field=models.CharField(
                blank=True, default="Unknown Browser", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_login_device",
            field=models.CharField(
                blank=True, default="Unknown Device", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="browser",
            field=models.CharField(
                blank=True, default="Unknown Browser", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="device",
            field=models.CharField(
                blank=True, default="Unknown Device", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user_agent",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
