# Generated by Django 6.0.5 on 2026-07-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_securityevent_location_securityevent_os_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminauditlog",
            name="browser",
            field=models.CharField(
                blank=True, default="Unknown Browser", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="adminauditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminauditlog",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_chat_limit",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_image_limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_token_limit",
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="daily_vision_limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unlimited_usage",
            field=models.BooleanField(default=False),
        ),
    ]
