# Generated by Django 6.0.5 on 2026-07-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_seed_feature_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("block", "block"),
                    ("unblock", "unblock"),
                    ("suspend", "suspend"),
                    ("unsuspend", "unsuspend"),
                    ("ban", "ban"),
                    ("unban", "unban"),
                    ("force_logout", "force_logout"),
                    ("delete_chats", "delete_chats"),
                    ("delete_uploads", "delete_uploads"),
                    ("reset_password", "reset_password"),
                    ("verify_email", "verify_email"),
                    ("change_role", "change_role"),
                    ("add_note", "add_note"),
                    ("feature_flag_toggle", "feature_flag_toggle"),
                    ("feature_flag_create", "feature_flag_create"),
                    ("broadcast_create", "broadcast_create"),
                    ("broadcast_deactivate", "broadcast_deactivate"),
                    ("delete_account", "delete_account"),
                    ("restore_account", "restore_account"),
                    ("export_user_data", "export_user_data"),
                    ("update_usage_limits", "update_usage_limits"),
                ],
                max_length=30,
            ),
        ),
    ]
