# Generated by Django 6.0.5 on 2026-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_userprofile_deleted_at_userprofile_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                    ("verified", "Verified User"),
                    ("user", "User"),
                ],
                db_index=True,
                default="user",
                max_length=20,
            ),
        ),
    ]
