# Generated by Django 6.0.5 on 2026-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_promote_owner_and_backfill_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("block", "block"),
                    ("unblock", "unblock"),
                    ("suspend", "suspend"),
                    ("unsuspend", "unsuspend"),
                    ("ban", "ban"),
                    ("unban", "unban"),
                    ("force_logout", "force_logout"),
                    ("delete_chats", "delete_chats"),
                    ("delete_uploads", "delete_uploads"),
                    ("reset_password", "reset_password"),
                    ("verify_email", "verify_email"),
                    ("change_role", "change_role"),
                    ("add_note", "add_note"),
                    ("feature_flag_toggle", "feature_flag_toggle"),
                    ("feature_flag_create", "feature_flag_create"),
                    ("broadcast_create", "broadcast_create"),
                    ("broadcast_deactivate", "broadcast_deactivate"),
                    ("delete_account", "delete_account"),
                    ("restore_account", "restore_account"),
                    ("export_user_data", "export_user_data"),
                    ("update_usage_limits", "update_usage_limits"),
                    ("ownership_transfer", "ownership_transfer"),
                    ("blocked_attempt", "blocked_attempt"),
                ],
                max_length=30,
            ),
        ),
    ]
