# Generated by Django 6.0.5 on 2026-07-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_add_csv_export_audit_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="dismissible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="is_popup",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("chat_provider", "Chat Provider"),
                            ("image_provider", "Image Provider"),
                            ("vision_provider", "Vision Provider"),
                            ("unhandled_exception", "Unhandled Exception"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("detail", models.TextField(blank=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["-last_seen"], name="chat_errorl_last_se_8fac39_idx"
                    ),
                    models.Index(
                        fields=["category", "resolved"],
                        name="chat_errorl_categor_19fbf4_idx",
                    ),
                ],
            },
        ),
    ]
