# Generated by Django 6.0.5 on 2026-07-17 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0029_add_more_audit_actions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="color_label",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("red", "Red"),
                    ("orange", "Orange"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="folder",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "is_archived", "-created_at"],
                name="chat_chatse_user_id_bcc122_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "folder"], name="chat_chatse_user_id_c048ea_idx"
            ),
        ),
    ]
