# Generated by Django 6.0.5 on 2026-07-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0030_add_chat_session_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone_auto",
            field=models.BooleanField(default=True),
        ),
    ]
