# Generated by Django 6.0.5 on 2026-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0033_savedprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
