# Generated by Django 6.0.5 on 2026-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0035_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("cyberpunk", "Cyber Dark (default)"),
                    ("midnight-purple", "Midnight"),
                    ("matrix-green", "Matrix"),
                    ("nord", "Nord"),
                    ("synthwave", "Synthwave"),
                    ("purple-neon", "Purple Neon"),
                    ("ocean", "Ocean"),
                    ("minimal-dark", "Minimal Dark"),
                    ("graphite", "Graphite"),
                    ("light", "Light"),
                    ("cyber-orange", "Cyber Orange"),
                    ("neon-green", "Neon Green"),
                    ("midnight-blue", "Midnight Blue"),
                    ("purple-matrix", "Purple Matrix"),
                    ("crimson-red", "Crimson Red"),
                    ("arctic-white", "Arctic White"),
                    ("oled-black", "OLED Black"),
                    ("emerald", "Emerald"),
                    ("royal-gold", "Royal Gold"),
                ],
                default="cyberpunk",
                max_length=20,
            ),
        ),
    ]
