# Generated by Django 6.0.5 on 2026-07-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0036_alter_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="accent_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Theme default"),
                    ("cyan", "Cyan"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                    ("gold", "Gold"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="animation_level",
            field=models.CharField(
                choices=[
                    ("full", "Full (default)"),
                    ("reduced", "Reduced"),
                    ("none", "None"),
                ],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="card_radius",
            field=models.CharField(
                choices=[
                    ("sharp", "Sharp"),
                    ("rounded", "Rounded (default)"),
                    ("soft", "Soft"),
                ],
                default="rounded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="density",
            field=models.CharField(
                choices=[("comfortable", "Comfortable"), ("compact", "Compact")],
                default="comfortable",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="glass_intensity",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("light", "Light"),
                    ("medium", "Medium (default)"),
                    ("high", "High"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
