# Generated by Django 6.0.5 on 2026-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0037_userprofile_accent_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="web_search_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
