# Generated by Django 6.0.5 on 2026-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0038_chatsession_web_search_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("chat", "chat"),
                    ("vision", "vision"),
                    ("image", "image"),
                    ("web_search", "web_search"),
                ],
                max_length=20,
            ),
        ),
    ]
