# Generated by Django 6.0.5 on 2026-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0039_alter_usageevent_event_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="web_search_enabled",
        ),
        migrations.AlterField(
            model_name="usageevent",
            name="event_type",
            field=models.CharField(
                choices=[("chat", "chat"), ("vision", "vision"), ("image", "image")],
                max_length=20,
            ),
        ),
    ]
