# Generated by Django 6.0.5 on 2026-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0040_remove_chatsession_web_search_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_model",
            field=models.CharField(default="quantum-core", max_length=50),
        ),
    ]
