# Generated by Django 6.0.5 on 2026-08-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0042_messageattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="default_model",
            field=models.CharField(default="ox-alpha", max_length=50),
        ),
    ]
