# Generated by Django 6.0.5 on 2026-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0043_alter_userprofile_default_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="agent_device_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agent_last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agent_platform",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agent_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
