# Generated by Django 6.0.5 on 2026-08-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0044_userprofile_agent_device_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="screen_awareness_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
