# Generated by Django 6.0.5 on 2026-08-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0045_userprofile_screen_awareness_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="session_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assistant", "Assistant"),
                    ("agent", "Agent Task"),
                    ("voice", "Voice Session"),
                    ("studio", "Studio Script"),
                ],
                db_index=True,
                default="assistant",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="VoiceStudioGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_text", models.TextField()),
                ("voice_name", models.CharField(default="default", max_length=100)),
                ("pitch", models.FloatField(default=1.0)),
                ("rate", models.FloatField(default=1.0)),
                ("volume", models.FloatField(default=1.0)),
                (
                    "preset_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("audio_data", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_studio_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chat_voices_user_id_be5796_idx",
                    )
                ],
            },
        ),
    ]
