# Generated by Django 6.0.5 on 2026-08-29 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0046_chatsession_session_type_voicestudiogeneration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session_created", "Created Conversation"),
                            ("message_sent", "Sent Message"),
                            ("prompt_used", "Used Prompt Template"),
                            ("bookmark_added", "Added Bookmark"),
                            ("highlight_saved", "Saved Highlight"),
                            ("model_switched", "Switched Model / Mode"),
                            ("export_performed", "Exported Conversation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "highlight_type",
                    models.CharField(
                        choices=[
                            ("answer", "Answer"),
                            ("code", "Code Snippet"),
                            ("decision", "Decision / Key Takeaway"),
                            ("task", "Action Item / Task"),
                            ("idea", "Idea / Concept"),
                            ("note", "Note"),
                        ],
                        default="answer",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="savedprompt",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="savedprompt",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userfact",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General Fact"),
                    ("preference", "Personal Preference"),
                    ("coding_style", "Coding & Architecture Style"),
                    ("instruction", "Custom AI Instruction"),
                    ("project", "Project Context"),
                ],
                default="general",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userfact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="savedprompt",
            index=models.Index(
                fields=["user", "category"], name="chat_savedp_user_id_745535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfact",
            index=models.Index(
                fields=["user", "category"], name="chat_userfa_user_id_ed4ff0_idx"
            ),
        ),
        migrations.AddField(
            model_name="activityevent",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_events",
                to="chat.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="activityevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationhighlight",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highlights",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="conversationhighlight",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="chat.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="conversationhighlight",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_activi_user_id_154642_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="chat_activi_event_t_49f11e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationhighlight",
            index=models.Index(
                fields=["user", "-created_at"], name="chat_conver_user_id_b49314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationhighlight",
            index=models.Index(
                fields=["session", "-created_at"], name="chat_conver_session_167f8a_idx"
            ),
        ),
    ]
