# Generated by Django 6.0.5 on 2026-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0047_activityevent_conversationhighlight_savedprompt_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="accent_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Theme default"),
                    ("gold", "Champagne Gold"),
                    ("mint", "ChatGPT Mint"),
                    ("terracotta", "Claude Terracotta"),
                    ("celestial", "Gemini Blue"),
                    ("emerald", "Imperial Emerald"),
                    ("sapphire", "Royal Sapphire"),
                    ("amethyst", "Crown Amethyst"),
                    ("cognac", "Bourbon Cognac"),
                    ("platinum", "Porsche Platinum"),
                    ("cyan", "Cyan"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("cyberpunk", "Cyber Dark (default)"),
                    ("royal-gold", "Royal Gold"),
                    ("chatgpt", "ChatGPT Dark"),
                    ("claude", "Claude Terracotta"),
                    ("gemini", "Gemini Cosmic"),
                    ("emerald-royale", "Rolex Emerald"),
                    ("monaco-grand", "Monaco 24K Gold"),
                    ("porsche-chalk", "Porsche Chalk"),
                    ("sapphire-vault", "Royal Sapphire"),
                    ("amethyst-royale", "Crown Amethyst"),
                    ("carbon-stealth", "Carbon Stealth"),
                    ("bourbon-cognac", "Bourbon Cognac"),
                    ("minimal-dark", "Minimal Dark"),
                    ("graphite", "Graphite"),
                    ("nord", "Nord"),
                    ("oled-black", "OLED Black"),
                    ("matrix-green", "Matrix"),
                    ("midnight-purple", "Midnight"),
                    ("synthwave", "Synthwave"),
                    ("purple-neon", "Purple Neon"),
                    ("neon-green", "Neon Green"),
                    ("crimson-red", "Crimson Red"),
                    ("emerald", "Emerald"),
                ],
                default="cyberpunk",
                max_length=20,
            ),
        ),
    ]
