# Generated by Django 6.0.5 on 2026-09-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0048_alter_userprofile_accent_override_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="accent_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Theme default"),
                    ("gold", "Monaco 24K Gold"),
                    ("mint", "ChatGPT Mint"),
                    ("terracotta", "Claude Terracotta"),
                    ("celestial", "Gemini Celestial Blue"),
                    ("platinum", "Porsche Platinum"),
                    ("emerald", "Imperial Emerald"),
                    ("cyan", "Cyan"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                    ("orange", "Orange"),
                    ("red", "Red"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("cyberpunk", "Cyber Dark (default)"),
                    ("chatgpt", "ChatGPT Dark"),
                    ("claude", "Claude Warm Dark"),
                    ("gemini", "Gemini Deep Cosmos"),
                    ("monaco-grand", "Monaco 24K Gold"),
                    ("porsche-chalk", "Porsche Chalk"),
                    ("carbon-stealth", "Carbon Stealth"),
                    ("minimal-dark", "Minimal Dark"),
                    ("graphite", "Graphite"),
                    ("nord", "Nord"),
                    ("oled-black", "OLED Black"),
                    ("midnight-purple", "Midnight"),
                    ("neon-green", "Neon Green"),
                    ("crimson-red", "Crimson Red"),
                    ("emerald", "Emerald"),
                ],
                default="cyberpunk",
                max_length=20,
            ),
        ),
    ]
